name: 'Citizen5 '
favicon: null
layout_spectrum: 0.19371860031969845
typography_spectrum: 0.6320442138239741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6317484062165022
  lightness: 0.525139452656731
  saturation: 0.2898055869154632
  rhythmicContrast: 0.14692029217258096
purpose: []
